package com.example.finalproject.navigation

const val ROUTE_ABOUT="about"
const val ROUTE_HOME="home"
const val ROUTE_LOGIN="login"
const val ROUTE_REGISTER="Register"
const val ROUTE_SCHEDULE="Schedule"
const val ROUTE_VIEW="View"
const val ROUTE_WASTEREDTIPS="wasteredtips"
const val ROUTE_CLOTHSWAP="clothswap"
const val ROUTE_COMPOSTWASTE ="compostwaste"
const val ROUTE_JUNKMAIL="junkmail"
const val ROUTE_REPAIR="repair"
const val ROUTE_REUSERBLECONT ="reusablecont"
const val ROUTE_SECONGHAND="secondhand"
const val ROUTE_ZEROWASTE="zerowaste"
const val ROUTE_BENEFITS = "benefits"
const val ROUTE_CHALLENGES = "challenges"
const val ROUTE_CURBSIDE ="curbside"
const val ROUTE_DROPOFF="dropoff"
const val ROUTE_EWASTE="ewaste"
const val ROUTE_RECYCLINGPROCESS ="recyclingprocess"
const val ROUTE_WHATISRECYCLED="whatisrecycled"
const val ROUTE_PREPARATION="preparation"
const val ROUTE_RECYCLING="recycling"
const val ROUTE_BINLOCATION="binlocation"
const val ROUTE_RECYCLINGINFO="recyclinginfo"